title: Sinerga-Optima
description: Post-capitalist upgrade path â€“ public tech guilds, worker co-ops, carbon caps.
baseurl: ""   # important: no sub-path
url: "https://sinerga-optima.org"
markdown: kramdown
highlighter: rouge

